spring:
  application:
    name: product-inventory-service
  profiles:
    active: local
  config:
    import: "configserver:"
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI}
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1

management:
  endpoints:
    web:
      exposure:
        include: "*"
